    server:
        port: 8080
    spring:
        datasource:
            url: jdbc:mysql://localhost/trainer
            password: 12345678
            username: root
        jpa:
            show-sql: true
            generate-ddl: true
            properties:
                hibernate:
                  show_sql: true
                  use_sql_comments: true
                  format_sql: true
                  type_sql: true
                  ddl-auto: update
        jackson:
            default-property-inclusion: NON_NULL
            date-format: dd-MM-yyyy HH:mm:ss
            time-zone: America/Sao_Paulo